import { FontCategory, GoogleFont } from "@/types";

// Extended Google Fonts list with additional popular options
export const googleFonts: GoogleFont[] = [
  // Sans-serif fonts
  { family: "Roboto", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Open Sans", category: "sans-serif", variants: ["300", "400", "600", "700"] },
  { family: "Lato", category: "sans-serif", variants: ["300", "400", "700", "900"] },
  { family: "Montserrat", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Source Sans 3", category: "sans-serif", variants: ["300", "400", "600", "700"] },
  { family: "Raleway", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Poppins", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Inter", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Work Sans", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "DM Sans", category: "sans-serif", variants: ["400", "500", "700"] },
  { family: "Nunito", category: "sans-serif", variants: ["300", "400", "600", "700"] },
  { family: "Quicksand", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Rubik", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Mulish", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Outfit", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Manrope", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Ubuntu", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Cabin", category: "sans-serif", variants: ["400", "500", "600", "700"] },
  { family: "Karla", category: "sans-serif", variants: ["300", "400", "500", "700"] },
  { family: "Public Sans", category: "sans-serif", variants: ["300", "400", "500", "700"] },

  // Serif fonts
  { family: "Merriweather", category: "serif", variants: ["300", "400", "700", "900"] },
  { family: "Playfair Display", category: "serif", variants: ["400", "500", "700", "900"] },
  { family: "Lora", category: "serif", variants: ["400", "500", "700"] },
  { family: "Source Serif 4", category: "serif", variants: ["300", "400", "600", "700"] },
  { family: "Crimson Text", category: "serif", variants: ["400", "600", "700"] },
  { family: "EB Garamond", category: "serif", variants: ["400", "500", "600", "700"] },
  { family: "Libre Baskerville", category: "serif", variants: ["400", "700"] },
  { family: "Cormorant Garamond", category: "serif", variants: ["300", "400", "500", "700"] },
  { family: "Spectral", category: "serif", variants: ["300", "400", "500", "700"] },
  { family: "PT Serif", category: "serif", variants: ["400", "700"] },
  { family: "Bree Serif", category: "serif", variants: ["400"] },
  { family: "Bitter", category: "serif", variants: ["300", "400", "500", "700"] },
  { family: "Arvo", category: "serif", variants: ["400", "700"] },

  // Monospace fonts
  { family: "Roboto Mono", category: "monospace", variants: ["300", "400", "500", "700"] },
  { family: "Source Code Pro", category: "monospace", variants: ["300", "400", "500", "700"] },
  { family: "IBM Plex Mono", category: "monospace", variants: ["300", "400", "500", "700"] },
  { family: "Fira Code", category: "monospace", variants: ["300", "400", "500", "700"] },
  { family: "JetBrains Mono", category: "monospace", variants: ["300", "400", "500", "700"] },
  { family: "Space Mono", category: "monospace", variants: ["400", "700"] },
  { family: "Ubuntu Mono", category: "monospace", variants: ["400", "700"] },
  { family: "Inconsolata", category: "monospace", variants: ["300", "400", "500", "700"] },
  { family: "Cousine", category: "monospace", variants: ["400", "700"] },

  // Display fonts
  { family: "Bebas Neue", category: "display", variants: ["400"] },
  { family: "Archivo Black", category: "display", variants: ["400"] },
  { family: "Anton", category: "display", variants: ["400"] },
  { family: "Oswald", category: "display", variants: ["300", "400", "500", "700"] },
  { family: "Teko", category: "display", variants: ["300", "400", "500", "700"] },
  { family: "Permanent Marker", category: "display", variants: ["400"] },
  { family: "Pacifico", category: "display", variants: ["400"] },
  { family: "Caveat", category: "display", variants: ["400", "500", "700"] },
  { family: "Comfortaa", category: "display", variants: ["300", "400", "500", "700"] },
];

// Categories for font combinations
export const fontCategories: FontCategory[] = [
  {
    name: "Corporate/Business",
    description:
      "Professional font combinations for business applications, corporate websites, and enterprise software",
    combinations: [
      {
        name: "Corporate Classic",
        description: "Traditional and reliable for established businesses",
        heading: "Roboto",
        body: "Open Sans",
        mono: "Roboto Mono",
      },
      {
        name: "Professional Modern",
        description: "Clean and contemporary for forward-thinking companies",
        heading: "Montserrat",
        body: "Source Sans 3",
        mono: "Source Code Pro",
      },
      {
        name: "Executive Suite",
        description: "Authoritative and polished for finance and legal",
        heading: "Merriweather",
        body: "Source Sans 3",
        mono: "IBM Plex Mono",
      },
      {
        name: "Consulting Firm",
        description: "Balanced and trustworthy for professional services",
        heading: "Raleway",
        body: "Lato",
        mono: "Source Code Pro",
      },
      {
        name: "Corporate Report",
        description: "Clear and legible for data-heavy business documents",
        heading: "Inter",
        body: "Inter",
        mono: "JetBrains Mono",
      },
      {
        name: "Enterprise Tech",
        description: "Modern and efficient for B2B and SaaS platforms",
        heading: "Work Sans",
        body: "Public Sans",
        mono: "IBM Plex Mono",
      },
    ],
  },
  {
    name: "Creative/Blog",
    description: "Expressive font combinations for blogs, portfolios, and creative content",
    combinations: [
      {
        name: "Literary Journal",
        description: "Elegant and readable for long-form content",
        heading: "Playfair Display",
        body: "Source Serif 4",
        mono: "Source Code Pro",
      },
      {
        name: "Creative Portfolio",
        description: "Bold and distinctive for showcasing design work",
        heading: "Poppins",
        body: "Work Sans",
        mono: "Space Mono",
      },
      {
        name: "Modern Blog",
        description: "Clean and versatile for various blog topics",
        heading: "Lora",
        body: "Open Sans",
        mono: "Roboto Mono",
      },
      {
        name: "Minimalist Writer",
        description: "Understated and focused for distraction-free reading",
        heading: "Spectral",
        body: "Karla",
        mono: "IBM Plex Mono",
      },
      {
        name: "Artistic Expression",
        description: "Unique and expressive for creative industries",
        heading: "Cormorant Garamond",
        body: "Mulish",
        mono: "Fira Code",
      },
      {
        name: "Magazine Style",
        description: "Editorial-inspired for content-rich platforms",
        heading: "EB Garamond",
        body: "Libre Baskerville",
        mono: "JetBrains Mono",
      },
    ],
  },
  {
    name: "E-commerce/Retail",
    description: "Accessible font combinations for online stores and retail experiences",
    combinations: [
      {
        name: "Modern Marketplace",
        description: "Clean and efficient for general e-commerce platforms",
        heading: "Manrope",
        body: "Inter",
        mono: "Source Code Pro",
      },
      {
        name: "Luxury Boutique",
        description: "Elegant and sophisticated for premium products",
        heading: "Playfair Display",
        body: "Quicksand",
        mono: "JetBrains Mono",
      },
      {
        name: "Accessible Shop",
        description: "Highly readable and inclusive for all users",
        heading: "Nunito",
        body: "Open Sans",
        mono: "Inconsolata",
      },
      {
        name: "Tech Store",
        description: "Modern and technical for gadgets and electronics",
        heading: "Outfit",
        body: "DM Sans",
        mono: "Fira Code",
      },
      {
        name: "Fashion Forward",
        description: "Stylish and trendy for fashion and apparel",
        heading: "Raleway",
        body: "Karla",
        mono: "Space Mono",
      },
      {
        name: "Handcrafted Goods",
        description: "Warm and personable for artisanal products",
        heading: "Bitter",
        body: "Source Sans 3",
        mono: "IBM Plex Mono",
      },
    ],
  },
  {
    name: "Technology/SaaS",
    description: "Modern font combinations for tech products, apps, and digital platforms",
    combinations: [
      {
        name: "Tech Startup",
        description: "Contemporary and cutting-edge for emerging tech",
        heading: "Inter",
        body: "Inter",
        mono: "Fira Code",
      },
      {
        name: "Developer Hub",
        description: "Technical and clear for documentation and code-heavy content",
        heading: "Rubik",
        body: "Source Sans 3",
        mono: "JetBrains Mono",
      },
      {
        name: "Enterprise SaaS",
        description: "Professional and scalable for business applications",
        heading: "Work Sans",
        body: "IBM Plex Sans",
        mono: "IBM Plex Mono",
      },
      {
        name: "Mobile App",
        description: "Crisp and readable on small screens",
        heading: "DM Sans",
        body: "DM Sans",
        mono: "Source Code Pro",
      },
      {
        name: "Analytics Dashboard",
        description: "Clear and data-focused for complex interfaces",
        heading: "Public Sans",
        body: "Roboto",
        mono: "Roboto Mono",
      },
      {
        name: "Modern Platform",
        description: "Clean and adaptable for various digital products",
        heading: "Outfit",
        body: "Mulish",
        mono: "Space Mono",
      },
    ],
  },
  {
    name: "Education/Learning",
    description: "Accessible font combinations for educational platforms and learning materials",
    combinations: [
      {
        name: "Academic Institution",
        description: "Traditional and authoritative for educational institutions",
        heading: "Merriweather",
        body: "Source Sans 3",
        mono: "Source Code Pro",
      },
      {
        name: "Digital Classroom",
        description: "Friendly and readable for e-learning platforms",
        heading: "Nunito",
        body: "Open Sans",
        mono: "Fira Code",
      },
      {
        name: "Scholarly Journal",
        description: "Formal and precise for academic content",
        heading: "Lora",
        body: "PT Serif",
        mono: "JetBrains Mono",
      },
      {
        name: "Child-Friendly Learning",
        description: "Approachable and clear for younger audiences",
        heading: "Quicksand",
        body: "Cabin",
        mono: "Inconsolata",
      },
      {
        name: "Technical Training",
        description: "Efficient and technical for skill-building platforms",
        heading: "Ubuntu",
        body: "Roboto",
        mono: "Ubuntu Mono",
      },
      {
        name: "Knowledge Base",
        description: "Clear and organized for reference materials",
        heading: "Work Sans",
        body: "Source Serif 4",
        mono: "IBM Plex Mono",
      },
    ],
  },
  {
    name: "Entertainment/Media",
    description: "Engaging font combinations for gaming, streaming, and media platforms",
    combinations: [
      {
        name: "Gaming Platform",
        description: "Bold and energetic for gaming experiences",
        heading: "Teko",
        body: "Rubik",
        mono: "JetBrains Mono",
      },
      {
        name: "Streaming Service",
        description: "Modern and accessible for video platforms",
        heading: "Outfit",
        body: "Nunito",
        mono: "Source Code Pro",
      },
      {
        name: "Podcast Network",
        description: "Warm and conversational for audio content",
        heading: "Montserrat",
        body: "Source Sans 3",
        mono: "Space Mono",
      },
      {
        name: "Film Festival",
        description: "Cinematic and stylish for film-related content",
        heading: "Oswald",
        body: "Lato",
        mono: "Roboto Mono",
      },
      {
        name: "Music Platform",
        description: "Vibrant and expressive for music and audio",
        heading: "Bebas Neue",
        body: "Work Sans",
        mono: "Fira Code",
      },
      {
        name: "News Media",
        description: "Clear and authoritative for news and journalism",
        heading: "Libre Baskerville",
        body: "Source Sans 3",
        mono: "IBM Plex Mono",
      },
    ],
  },
];
